name: Deploy to GitHub Pages

on:
  push:
    branches: [ "main" ]  # Ou "master" se sua branch principal for master

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Esta etapa é opcional - só necessário se você tiver dependências
      - name: Install dependencies
        run: |
          npm install
          
      - name: Build (opcional)
        run: |
          echo "Não há etapa de build neste projeto puro HTML/CSS/JS"
          # Se no futuro tiver build steps (ex: npm run build), coloque aqui

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: './public'  # A pasta que contém seus arquivos HTML

  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    runs-on: ubuntu-latest
    
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
